Repository uswLectureEvaluation/SUWIKI-Spring, pull requests merged in 2023-12, with the labels that each got.

#38 docs: PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: good first issue

#39 refactor: 프로파일 분리
  .gitignore
  src/main/resources/application.yml
Labels: enhancement

#40 feat: CI CD (develop)
  .github/workflows/deploy-develop.yml
  Dockerfile.dev
Labels: enhancement

#41 feat: 헬스 체크 API
  .github/workflows/deploy-develop.yml
  dev.Dockerfile
  src/main/java/usw/suwiki/HealthCheckController.java
Labels: enhancement

#47 fix: 테스트를 위한 gradle 설정 변경
  .github/workflows/ci-cd.yml
  build.gradle
Labels: ✅ fix

#49 refactor: CI CD PR 트리거 삭제
  .github/workflows/deploy-main.yml
Labels: 🔍 refactor

#48 release: 개발 설정 및 CI CD 수정 작업 배포
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy-develop.yml
  .github/workflows/deploy-main.yml
  .gitignore
  build.gradle
  dev.Dockerfile
  src/main/java/usw/suwiki/HealthCheckController.java
  src/main/resources/application.yml
Labels: :rocket: release

#50 test: 초기 설정
  src/test/java/usw/suwiki/config/TestJpaConfig.java
  src/test/java/usw/suwiki/template/user/UserTemplate.java
Labels: 🌿 feature

#42 refactor: FavoriteMajor Repository springDataJPA로 변환
  src/main/java/usw/suwiki/domain/favoritemajor/FavoriteMajor.java
  src/main/java/usw/suwiki/domain/favoritemajor/controller/FavoriteMajorControllerV2.java
  src/main/java/usw/suwiki/domain/favoritemajor/repository/FavoriteMajorRepository.java
  src/main/java/usw/suwiki/domain/favoritemajor/repository/FavoriteMajorRepositoryV2.java
  src/main/java/usw/suwiki/domain/favoritemajor/repository/JpaFavoriteMajorRepository.java
  src/main/java/usw/suwiki/domain/favoritemajor/service/FavoriteMajorService.java
  src/main/java/usw/suwiki/domain/favoritemajor/service/FavoriteMajorServiceV2.java
  src/main/java/usw/suwiki/domain/user/user/service/UserBusinessService.java
  src/main/java/usw/suwiki/domain/user/user/service/UserCRUDService.java
  src/main/java/usw/suwiki/domain/user/user/service/UserSchedulingService.java
  src/main/java/usw/suwiki/domain/user/userIsolation/service/UserIsolationSchedulingService.java
  src/main/java/usw/suwiki/global/exception/ExceptionType.java
  src/main/java/usw/suwiki/global/exception/errortype/FavoriteMajorException.java
  src/test/java/usw/suwiki/service/favoriteMajor/FavoriteMajorServiceV2Test.java
  src/test/java/usw/suwiki/template/favoriteMajor/FavoriteMajorTemplate.java
Labels: 🔍 refactor

#53 hotfix: 강의 평가 생성/수정시 강의 조회 에러 해결
  src/main/java/usw/suwiki/domain/evaluatepost/domain/EvaluatePost.java
  src/main/java/usw/suwiki/domain/lecture/domain/Lecture.java
  src/main/java/usw/suwiki/domain/lecture/domain/repository/LectureRepository.java
  src/main/java/usw/suwiki/domain/lecture/service/LectureCRUDService.java
  src/main/java/usw/suwiki/domain/user/user/User.java
  src/test/java/usw/suwiki/repository/lecture/LectureRepositoryTest.java
  src/test/java/usw/suwiki/template/evaluatepost/EvaluatePostTemplate.java
  src/test/java/usw/suwiki/template/lecture/LectureDetailTemplate.java
  src/test/java/usw/suwiki/template/lecture/LectureTemplate.java
Labels: 🚨 hotfix

#55 hotfix: 토큰 재발급 에러
  src/main/java/usw/suwiki/domain/refreshtoken/service/RefreshTokenCRUDService.java
  src/main/java/usw/suwiki/domain/user/user/service/UserBusinessService.java
  src/main/java/usw/suwiki/global/jwt/JwtAgent.java
Labels: 🚨 hotfix
