Repository uswLectureEvaluation/SUWIKI-Spring, pull requests merged in 2024-02, with the labels that each got.

#75 hotfix : CORS 설정 누락
  README.md
  src/main/java/usw/suwiki/domain/timetable/controller/TimetableController.java
  src/main/java/usw/suwiki/domain/user/user/controller/UserController.java
  src/main/java/usw/suwiki/global/version/VersionController.java
Labels: 🚨 hotfix

#77 feat: 학기 프로퍼티 2024 1학기로 변경
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🌿 feature

#79 hotfix: 시간표상 강의 조회 오류 해결 및 강의 테이블 구조 변경
  src/main/java/usw/suwiki/domain/lecture/controller/dto/LectureWithScheduleResponse.java
  src/main/java/usw/suwiki/domain/lecture/domain/Lecture.java
  src/main/java/usw/suwiki/domain/lecture/domain/LectureDetail.java
  src/main/java/usw/suwiki/domain/lecture/domain/LectureSchedule.java
  src/main/java/usw/suwiki/domain/lecture/domain/repository/LectureCustomRepository.java
  src/main/java/usw/suwiki/domain/lecture/domain/repository/LectureCustomRepositoryImpl.java
  src/main/java/usw/suwiki/domain/lecture/domain/repository/LectureScheduleRepository.java
  src/main/java/usw/suwiki/domain/lecture/service/LectureService.java
  src/main/java/usw/suwiki/global/util/loadjson/JSONLectureVO.java
  src/test/java/usw/suwiki/domain/lecture/fixture/LectureDetailFixture.java
  src/test/java/usw/suwiki/domain/lecture/repository/LectureRepositoryTest.java
  src/test/java/usw/suwiki/domain/lecture/service/InsertNewLectureTest.java
  src/test/java/usw/suwiki/domain/lecture/service/LectureServiceTest.java
Labels: 🚨 hotfix

#80 hotfix: 강의 시간표상 시간 미정된 강의들에 대한 누락 문제
  src/main/java/usw/suwiki/domain/lecture/service/LectureService.java
  src/main/java/usw/suwiki/domain/lecture/util/LectureStringConverter.java
  src/main/java/usw/suwiki/global/util/loadjson/JSONLectureVO.java
  src/main/java/usw/suwiki/global/util/loadjson/USWTermResolver.java
Labels: 🚨 hotfix

#83 docs: infra 구성도 이미지를 재업로드합니다.
  README.md
Labels: 📔 docs

#85 refactor : 홈 API 응답 시 eTag를 추가합니다.
  src/main/java/usw/suwiki/domain/lecture/controller/LectureController.java
  src/main/java/usw/suwiki/global/config/ETagConfig.java
Labels: 🔍 refactor

#86 feat: 액츄에이터 추가
  build.gradle
  src/main/java/usw/suwiki/global/config/ActuatorHttpExchangeConfig.java
Labels: 🌿 feature
